# Generated by Django 5.1.5 on 2025-03-08 21:42

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', api.models.CustomUserManager()),
            ],
        ),
    ]
