# Generated by Django 5.1.7 on 2025-04-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptedarea',
            old_name='last_name',
            new_name='adoptee_name',
        ),
        migrations.RenameField(
            model_name='adoptedarea',
            old_name='first_name',
            new_name='area_name',
        ),
    ]
