# Generated by Django 5.1.7 on 2025-04-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_last_name_adoptedarea_adoptee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptedarea',
            name='adoption_type',
            field=models.CharField(choices=[('indefinite', 'Indefinite'), ('temporary', 'Temporary')], default='indefinite', max_length=20),
        ),
        migrations.AddField(
            model_name='adoptedarea',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptedarea',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
