# Generated by Django 5.1.7 on 2025-04-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_managers'),
        ('api', '0004_adoptedarea_adoption_type_adoptedarea_end_date_and_more'),
    ]

    operations = [
    ]
