# Generated by Django 5.1.5 on 2025-05-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_managers'),
        ('api', '0005_adoptedarea_adoption_type_adoptedarea_end_date_and_more'),
    ]

    operations = [
    ]
