# Generated by Django 5.2.1 on 2025-05-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20250419_2222'),
        ('api', '0007_adoptedarea_location'),
    ]

    operations = [
    ]
