# Generated by Django 5.1.5 on 2025-05-17 20:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_adoptedarea_lat_remove_adoptedarea_lng_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptedarea',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', srid=4326),
            preserve_default=False,
        ),
    ]
